<a href="https://colab.research.google.com/github/sewaadekunle/Sales-Performance-Analysis-Using-SQL/blob/main/Second_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mlt
import seaborn as sns

In [65]:
df = pd.read_csv('/content/drive/MyDrive/transactions_for_fe.csv')
df

,TransactionID,CustomerID,CustomerName,City,SignupDate,OrderDate,Category,Product,Quantity,UnitPrice,PaymentMethod,Channel
0,9041,6011,Ifeoma Adeyemi,Benin City,2023-06-14,2025-08-31,Haircare,Argan Oil,4,5232,Mobile Money,WhatsApp
1,9130,6034,Segun Suleiman,Lagos,2023-10-22,2025-06-28,Haircare,Shampoo 500ml,4,2891,POS,WhatsApp
2,9072,6018,Bola Chukwu,Benin City,2024-05-28,2024-06-27,Haircare,Shampoo 500ml,2,2947,Cash,WhatsApp
3,9032,6006,Obinna Nwosu,Enugu,2023-02-13,2025-08-19,Skincare,Shea Butter Cream,4,2897,POS,Website
4,9179,6042,Yemi Chukwu,Kano,2024-03-12,2024-04-10,Wellness,Essential Oil Set,1,6756,POS,Instagram
...,...,...,...,...,...,...,...,...,...,...,...,...
278,9148,6035,Tolu Bello,Enugu,2023-10-24,2024-12-14,Skincare,Aloe Vera Gel,2,2632,Cash,WhatsApp
279,9107,6030,Tunde Adeyemi,Abuja,2024-05-17,2025-12-26,Wellness,Detox Tea,4,3273,Mobile Money,Website
280,9261,6065,Bola Afolabi,Lagos,2024-09-23,2025-04-12,Makeup,Eyeliner Pencil,4,1433,Mobile Money,Walk-in
281,9063,6016,Zainab Lawal,Ibadan,2023-12-16,2024-06-28,Wellness,Bath Salt,1,2191,Mobile Money,Website
282,9114,6031,Ronke Lawal,Enugu,2023-09-11,2024-11-11,Haircare,Hair Relaxer Kit,1,6436,Bank Transfer,WhatsApp

In [66]:
df.dtypes

TransactionID     int64
CustomerID        int64
CustomerName     object
City             object
SignupDate       object
OrderDate        object
Category         object
Product          object
Quantity          int64
UnitPrice         int64
PaymentMethod    object
Channel          object
dtype: object

In [67]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'], errors = 'coerce')
df['SignupDate'] = pd.to_datetime(df['SignupDate'], errors = 'coerce')
df.dtypes

TransactionID             int64
CustomerID                int64
CustomerName             object
City                     object
SignupDate       datetime64[ns]
OrderDate        datetime64[ns]
Category                 object
Product                  object
Quantity                  int64
UnitPrice                 int64
PaymentMethod            object
Channel                  object
dtype: object

In [68]:
print(f'There are {df.duplicated().sum()} duplicates')
print(f'Missing values in each column: {df.isnull().sum()}')

There are 0 duplicates
Missing values in each column: TransactionID    0
CustomerID       0
CustomerName     0
City             0
SignupDate       0
OrderDate        0
Category         0
Product          0
Quantity         0
UnitPrice        0
PaymentMethod    0
Channel          0
dtype: int64

In [69]:
# Calculate Total Sales on each order
df['TotalSales'] = df['Quantity'] * df['UnitPrice']
df

,TransactionID,CustomerID,CustomerName,City,SignupDate,OrderDate,Category,Product,Quantity,UnitPrice,PaymentMethod,Channel,TotalSales
0,9041,6011,Ifeoma Adeyemi,Benin City,2023-06-14,2025-08-31,Haircare,Argan Oil,4,5232,Mobile Money,WhatsApp,20928
1,9130,6034,Segun Suleiman,Lagos,2023-10-22,2025-06-28,Haircare,Shampoo 500ml,4,2891,POS,WhatsApp,11564
2,9072,6018,Bola Chukwu,Benin City,2024-05-28,2024-06-27,Haircare,Shampoo 500ml,2,2947,Cash,WhatsApp,5894
3,9032,6006,Obinna Nwosu,Enugu,2023-02-13,2025-08-19,Skincare,Shea Butter Cream,4,2897,POS,Website,11588
4,9179,6042,Yemi Chukwu,Kano,2024-03-12,2024-04-10,Wellness,Essential Oil Set,1,6756,POS,Instagram,6756
...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,9148,6035,Tolu Bello,Enugu,2023-10-24,2024-12-14,Skincare,Aloe Vera Gel,2,2632,Cash,WhatsApp,5264
279,9107,6030,Tunde Adeyemi,Abuja,2024-05-17,2025-12-26,Wellness,Detox Tea,4,3273,Mobile Money,Website,13092
280,9261,6065,Bola Afolabi,Lagos,2024-09-23,2025-04-12,Makeup,Eyeliner Pencil,4,1433,Mobile Money,Walk-in,5732
281,9063,6016,Zainab Lawal,Ibadan,2023-12-16,2024-06-28,Wellness,Bath Salt,1,2191,Mobile Money,Website,2191
282,9114,6031,Ronke Lawal,Enugu,2023-09-11,2024-11-11,Haircare,Hair Relaxer Kit,1,6436,Bank Transfer,WhatsApp,6436

In [70]:
# How many days (Tenure days) did it take customers to make their first purchase after they sign up?

df['TenureDays'] = df['OrderDate'] - df['SignupDate']
df

,TransactionID,CustomerID,CustomerName,City,SignupDate,OrderDate,Category,Product,Quantity,UnitPrice,PaymentMethod,Channel,TotalSales,TenureDays
0,9041,6011,Ifeoma Adeyemi,Benin City,2023-06-14,2025-08-31,Haircare,Argan Oil,4,5232,Mobile Money,WhatsApp,20928,809 days
1,9130,6034,Segun Suleiman,Lagos,2023-10-22,2025-06-28,Haircare,Shampoo 500ml,4,2891,POS,WhatsApp,11564,615 days
2,9072,6018,Bola Chukwu,Benin City,2024-05-28,2024-06-27,Haircare,Shampoo 500ml,2,2947,Cash,WhatsApp,5894,30 days
3,9032,6006,Obinna Nwosu,Enugu,2023-02-13,2025-08-19,Skincare,Shea Butter Cream,4,2897,POS,Website,11588,918 days
4,9179,6042,Yemi Chukwu,Kano,2024-03-12,2024-04-10,Wellness,Essential Oil Set,1,6756,POS,Instagram,6756,29 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,9148,6035,Tolu Bello,Enugu,2023-10-24,2024-12-14,Skincare,Aloe Vera Gel,2,2632,Cash,WhatsApp,5264,417 days
279,9107,6030,Tunde Adeyemi,Abuja,2024-05-17,2025-12-26,Wellness,Detox Tea,4,3273,Mobile Money,Website,13092,588 days
280,9261,6065,Bola Afolabi,Lagos,2024-09-23,2025-04-12,Makeup,Eyeliner Pencil,4,1433,Mobile Money,Walk-in,5732,201 days
281,9063,6016,Zainab Lawal,Ibadan,2023-12-16,2024-06-28,Wellness,Bath Salt,1,2191,Mobile Money,Website,2191,195 days
282,9114,6031,Ronke Lawal,Enugu,2023-09-11,2024-11-11,Haircare,Hair Relaxer Kit,1,6436,Bank Transfer,WhatsApp,6436,427 days

In [71]:
# How many total orders does each customer have?
total_orders = df.groupby('CustomerID')['TransactionID'].count()
df['CustomerTotalOrder'] = df['CustomerID'].map(total_orders)

# Total amount each customer has ever spent, attached to every one of their rows
total_spent = df.groupby('CustomerID')['TotalSales'].sum()
df['CustomerLifetimeValue'] = df['CustomerID'].map(total_spent)

df.head(2)

,TransactionID,CustomerID,CustomerName,City,SignupDate,OrderDate,Category,Product,Quantity,UnitPrice,PaymentMethod,Channel,TotalSales,TenureDays,CustomerTotalOrder,CustomerLifetimeValue
0,9041,6011,Ifeoma Adeyemi,Benin City,2023-06-14,2025-08-31,Haircare,Argan Oil,4,5232,Mobile Money,WhatsApp,20928,809 days,4,50398
1,9130,6034,Segun Suleiman,Lagos,2023-10-22,2025-06-28,Haircare,Shampoo 500ml,4,2891,POS,WhatsApp,11564,615 days,12,90313

In [72]:
# #IsRepeatCustomer A trueor false flag: does this CustomerID have more than 1 order
def IsRepeatCustomer (total_order):
  if total_order > 1:
    return True
  else:
    return False


df['IsRepeatCustomer'] = df['CustomerTotalOrder'].apply(IsRepeatCustomer)
df

,TransactionID,CustomerID,CustomerName,City,SignupDate,OrderDate,Category,Product,Quantity,UnitPrice,PaymentMethod,Channel,TotalSales,TenureDays,CustomerTotalOrder,CustomerLifetimeValue,IsRepeatCustomer
0,9041,6011,Ifeoma Adeyemi,Benin City,2023-06-14,2025-08-31,Haircare,Argan Oil,4,5232,Mobile Money,WhatsApp,20928,809 days,4,50398,True
1,9130,6034,Segun Suleiman,Lagos,2023-10-22,2025-06-28,Haircare,Shampoo 500ml,4,2891,POS,WhatsApp,11564,615 days,12,90313,True
2,9072,6018,Bola Chukwu,Benin City,2024-05-28,2024-06-27,Haircare,Shampoo 500ml,2,2947,Cash,WhatsApp,5894,30 days,5,35898,True
3,9032,6006,Obinna Nwosu,Enugu,2023-02-13,2025-08-19,Skincare,Shea Butter Cream,4,2897,POS,Website,11588,918 days,4,57580,True
4,9179,6042,Yemi Chukwu,Kano,2024-03-12,2024-04-10,Wellness,Essential Oil Set,1,6756,POS,Instagram,6756,29 days,12,114106,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,9148,6035,Tolu Bello,Enugu,2023-10-24,2024-12-14,Skincare,Aloe Vera Gel,2,2632,Cash,WhatsApp,5264,417 days,12,93323,True
279,9107,6030,Tunde Adeyemi,Abuja,2024-05-17,2025-12-26,Wellness,Detox Tea,4,3273,Mobile Money,Website,13092,588 days,3,20427,True
280,9261,6065,Bola Afolabi,Lagos,2024-09-23,2025-04-12,Makeup,Eyeliner Pencil,4,1433,Mobile Money,Walk-in,5732,201 days,3,18201,True
281,9063,6016,Zainab Lawal,Ibadan,2023-12-16,2024-06-28,Wellness,Bath Salt,1,2191,Mobile Money,Website,2191,195 days,4,36664,True
282,9114,6031,Ronke Lawal,Enugu,2023-09-11,2024-11-11,Haircare,Hair Relaxer Kit,1,6436,Bank Transfer,WhatsApp,6436,427 days,12,89477,True

In [73]:
# OrderMonth / OrderWeekday
df['OrderMonth'] = df['OrderDate'].dt.month_name()
df['OrderWeekday'] = df['OrderDate'].dt.day_name()
df.head()

,TransactionID,CustomerID,CustomerName,City,SignupDate,OrderDate,Category,Product,Quantity,UnitPrice,PaymentMethod,Channel,TotalSales,TenureDays,CustomerTotalOrder,CustomerLifetimeValue,IsRepeatCustomer,OrderMonth,OrderWeekday
0,9041,6011,Ifeoma Adeyemi,Benin City,2023-06-14,2025-08-31,Haircare,Argan Oil,4,5232,Mobile Money,WhatsApp,20928,809 days,4,50398,True,August,Sunday
1,9130,6034,Segun Suleiman,Lagos,2023-10-22,2025-06-28,Haircare,Shampoo 500ml,4,2891,POS,WhatsApp,11564,615 days,12,90313,True,June,Saturday
2,9072,6018,Bola Chukwu,Benin City,2024-05-28,2024-06-27,Haircare,Shampoo 500ml,2,2947,Cash,WhatsApp,5894,30 days,5,35898,True,June,Thursday
3,9032,6006,Obinna Nwosu,Enugu,2023-02-13,2025-08-19,Skincare,Shea Butter Cream,4,2897,POS,Website,11588,918 days,4,57580,True,August,Tuesday
4,9179,6042,Yemi Chukwu,Kano,2024-03-12,2024-04-10,Wellness,Essential Oil Set,1,6756,POS,Instagram,6756,29 days,12,114106,True,April,Wednesday

**Analysis Question**

In [84]:
#Do repeat customers spend more per order on average than one-time customers?
x = df.groupby('IsRepeatCustomer')[['TotalSales']].mean().round(2)
print(x)

                  TotalSales
IsRepeatCustomer
False                8703.50
True                 7666.04

In [85]:
# Which acquisition Channel produces the most loyal (highest OrderCount) customers?
y = df.groupby('Channel')['TransactionID'].count()
print(y)

Channel
Instagram    67
Referral     51
Walk-in      49
Website      48
WhatsApp     68
Name: TransactionID, dtype: int64

In [ ]:
#Is there a relationship between TenureDays and order size — do longer-term customers buy more per visit?

In [88]:
#Which city has the highest customer lifetime value on average?
z = df.groupby('City')['CustomerLifetimeValue'].mean().round(2)
z

City
Abuja            22981.00
Benin City       35430.23
Enugu            69212.20
Ibadan           40677.31
Kano             54818.90
Lagos            68850.18
Port Harcourt    43760.58
Name: CustomerLifetimeValue, dtype: float64